export const SET_AUTH_USER = "AUTH_USER";
export const UNSET_AUTH_USER = "UNSET_AUTH_USER";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const RECIEVE_QUESTION = " RECIEVE_QUESTION";

export const RECIEVE_USERS = "RECIEVE_USERS";

export const TOGGLE_VOTE = "TOGGLE_VOTE";

export const ANSWERED_QUESTION = "ANSWERED_QUESTION";
